### ISSUE TITLE
Tell me

### ISSUE THREAD

**Issue by mironov1338** [okhsunrog/esp_ws28xx#2]
Hi, I'm looking at your code and would like to ask what it means to you
![image](https://github.com/user-attachments/assets/dbc2e3e5-b49a-40db-85db-6e3cd8b4283e)

typedef struct {
    union {
        struct {
            union {
                uint8_t r;
                uint8_t red;
            };

            union {
                uint8_t g;
                uint8_t green;
            };

            union {
                uint8_t b;
                uint8_t blue;
            };
        };

        uint8_t raw[3];    // What does it mean?
        uint32_t num;    // What does it mean?
    };
} CRGB;

**Comment by okhsunrog** [comment]
@mironov1338 hi. Actually I copied the type from the lib I forked mine from: https://github.com/8-DK/ESP32_SPI_WS2812_idf

I can explain to you, what it means. It's union, so it's just another handy way to address the fields of the struct. You can call then by names of colors, .red or .r, or you can call them by index, if you want, for example, for some reason iterate over them in an array. uint32_t num could be handy for "serialization", when you want so save the pixel as one integer value. Unions in C give you a way to access bytes of data in a different way. It has no overhead, doesn't increase size of CRGB struct and it's there because I thought it might be handy sometimes in the feature.

**Comment by mironov1338** [comment]
Thx bro>< you a monster!
